chore(jassob): update wchat script

diff --git a/jassob/.local/bin/wchat b/jassob/.local/bin/wchat
--- a/jassob/.local/bin/wchat
+++ b/jassob/.local/bin/wchat
@@ -1,12 +1,18 @@
 #!/usr/bin/env nix-shell
-#! nix-shell -i bash -p python39Packages.notify2 python39Packages.dbus-python python39 mosh
+#! nix-shell -i bash -p python312Packages.notify2 python312Packages.dbus-python python312
 
 set -euo pipefail
 
 cd "${HOME}/tools/weelisten" || { echo "Missing weelisten, clone github.com/Jassob/weelisten"; exit 1; }
+if CERT_MOD_TIME=$(stat -c '%Y' ./fullchain.pem) && \
+   (( (( $(date +%s) - $CERT_MOD_TIME )) < 86400 )); then
+   echo "Recent certificate detected, remove $(pwd)/fullchain.pem if connection attempts fails"
+else
+  scp -P222 jassob.se:.weechat/ssl/fullchain.pem ./fullchain.pem
+fi
 python3 client.py jassob.se --password-cmd "pass apps/weechat | tail -n +3 | cut -f 3 -d ' '" \
                             --ca-file "~/tools/weelisten/fullchain.pem" \
                             --port 8001 &
-IP=$(ping -c 1 192.168.1.72 >/dev/null && echo 192.168.1.72 || echo nuc)
-mosh ${IP} tmux a
+IP=$(ping -c 1 192.168.1.72 >/dev/null && echo 192.168.1.72 || echo jassob.se)
+ssh -p222 -t ${IP} tmux a
 trap 'kill $(jobs -p)' EXIT
